services:
  # web:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  
  comment:
    build:
      context: ./ia-comentarios
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./ia-comentarios:/app
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build:
      context: ./ia-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ia-service:/app
    environment:
      - PYTHONUNBUFFERED=1
