services:
  ia-service:
    build: ./ia-service
    container_name: ia-service
    ports:
      - "8000:8000"
    env_file:
      - ./ia-service/.env
  app:
    build: ./app
    container_name: app
    ports:
      - "8001:8000"
    env_file:
      - ./ia-service/.env
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8002:8000"
    env_file:
      - ./backend/.env
  api-back:
    build: ./api
    container_name: api
    ports:
      - "8003:3000"
    env_file:
      - ./api/.env
    depends_on:
      - backend